<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PanelCladdingEditor</RootNamespace>
    <AssemblyName>PanelCladdingEditor</AssemblyName>
    <TargetExt Condition="'$(PanelCladdingTestHost)' != 'true'">.rhp</TargetExt>
    <TargetExt Condition="'$(PanelCladdingTestHost)' == 'true'">.dll</TargetExt>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseSystemDrawing>true</UseSystemDrawing>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj-testhost/**;bin-testhost/**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon" Aliases="rhinocommon">
      <HintPath>C:\Program Files\Rhino 8\System\netcore\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rhino.UI">
      <HintPath>C:\Program Files\Rhino 8\System\netcore\Rhino.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Eto">
      <HintPath>C:\Program Files\Rhino 8\System\Eto.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
